import type { CompensationEntry, FlatEntry } from './types';

/**
 * Flat vocabularies: small, stable, closed sets where a hierarchy would be
 * false precision.
 */

export const CUSTOMER_TYPES: FlatEntry[] = [
  {
    slug: 'smb',
    name: 'Small Business',
    description: 'Roughly 1–50 employees. Short cycles, owner is usually the buyer.',
  },
  {
    slug: 'mid-market',
    name: 'Mid-Market',
    description: 'Roughly 51–1,000 employees. Committee buying, defined procurement.',
  },
  {
    slug: 'enterprise',
    name: 'Enterprise',
    description: '1,000+ employees. Long cycles, multiple stakeholders, formal RFPs.',
  },
  {
    slug: 'government',
    name: 'Government & Public Sector',
    description: 'Federal, state, provincial and municipal. Procurement rules apply.',
  },
  {
    slug: 'healthcare-providers',
    name: 'Healthcare Providers & Systems',
    description: 'Hospitals, clinics, practices and integrated delivery networks.',
  },
  {
    slug: 'education',
    name: 'Education & Academic',
    description: 'Schools, districts, colleges and universities.',
  },
  {
    slug: 'channel-partners',
    name: 'Channel, Reseller & Distributor',
    description: 'Selling through partners rather than direct to the end user.',
  },
  {
    slug: 'consumer',
    name: 'Consumer (B2C)',
    description: 'Selling directly to individuals.',
  },
];

export const SALES_MODELS: FlatEntry[] = [
  {
    slug: 'inside-sales',
    name: 'Inside Sales',
    description: 'Sold remotely by phone, email and video. No routine travel.',
  },
  {
    slug: 'field-sales',
    name: 'Field / Outside Sales',
    description: 'In-person selling, territory travel, on-site meetings.',
  },
  {
    slug: 'outbound-hunting',
    name: 'Outbound / Hunting',
    description: 'Self-generated pipeline through cold outreach and prospecting.',
  },
  {
    slug: 'inbound-closing',
    name: 'Inbound / Closing',
    description: 'Working leads generated by marketing rather than sourcing them.',
  },
  {
    slug: 'account-management',
    name: 'Account Management / Farming',
    description: 'Growing and retaining existing accounts rather than winning new ones.',
  },
  {
    slug: 'channel-sales',
    name: 'Channel & Partner Sales',
    description: 'Recruiting and enabling resellers, distributors and partners.',
  },
  {
    slug: 'business-development',
    name: 'Business Development & Partnerships',
    description: 'Strategic alliances, referral networks and new market entry.',
  },
  {
    slug: 'solution-selling',
    name: 'Solution & Technical Selling',
    description: 'Consultative, technically involved sales with proof-of-concept work.',
  },
];

export const COMPENSATION_TYPES: CompensationEntry[] = [
  {
    slug: 'commission-only',
    name: 'Commission Only',
    description: 'Paid purely on results. No guaranteed income.',
    hasGuaranteedPay: false,
  },
  {
    slug: 'base-plus-commission',
    name: 'Base + Commission',
    description: 'A guaranteed base salary plus performance commission.',
    hasGuaranteedPay: true,
  },
  {
    slug: 'draw-against-commission',
    name: 'Draw Against Commission',
    description:
      'Regular advance payments offset against future commission. Provides cash flow while a pipeline builds.',
    hasGuaranteedPay: true,
  },
  {
    slug: 'retainer',
    name: 'Retainer',
    description: 'A fixed recurring fee for an agreed scope of work.',
    hasGuaranteedPay: true,
  },
  {
    slug: 'retainer-plus-commission',
    name: 'Retainer + Commission',
    description: 'A fixed recurring fee plus upside on results. Common for fractional roles.',
    hasGuaranteedPay: true,
  },
  {
    slug: 'fractional',
    name: 'Fractional (Fixed Monthly)',
    description: 'A defined number of hours or days per month at a fixed rate.',
    hasGuaranteedPay: true,
  },
  {
    slug: 'contract-project',
    name: 'Contract / Project Fee',
    description: 'A fixed fee for a defined project or engagement period.',
    hasGuaranteedPay: true,
  },
];
