-- ===========================================================================
-- 0008_taxonomy_seed
--
-- GENERATED FILE — DO NOT EDIT BY HAND.
--
-- Source:    src/lib/taxonomy/seed/*.ts
-- Regenerate: pnpm db:generate-seed
--
-- CI regenerates this file and fails if the result differs from what is
-- committed, so the SQL and the TypeScript source cannot drift apart.
--
-- Adding entries later is INSERT-only work — a new industry, sub-category or
-- whole branch needs no schema change and no migration of user data. Slugs are
-- permanent; retire an entry with is_active = false rather than deleting it.
--
-- Contents:
--   industries          142
--   product_categories  68
--   territories         211
--   customer_types      8
--   sales_models        8
--   compensation_types  7
-- ===========================================================================

-- industries: 142 entries
-- depth 0
insert into industries (slug, name, description, parent_id, sort_order) values
  ('software-technology', 'Software & Technology', null, null, 0),
  ('healthcare-life-sciences', 'Healthcare & Life Sciences', null, null, 10),
  ('financial-services', 'Financial Services', null, null, 20),
  ('insurance', 'Insurance', null, null, 30),
  ('manufacturing-industrial', 'Manufacturing & Industrial', null, null, 40),
  ('construction-building', 'Construction & Building Products', null, null, 50),
  ('consumer-goods-retail', 'Consumer Goods & Retail', null, null, 60),
  ('food-beverage', 'Food & Beverage', null, null, 70),
  ('energy-utilities', 'Energy & Utilities', null, null, 80),
  ('transportation-logistics', 'Transportation & Logistics', null, null, 90),
  ('real-estate-property', 'Real Estate & Property', null, null, 100),
  ('professional-services', 'Professional Services', null, null, 110),
  ('marketing-advertising', 'Marketing & Advertising', null, null, 120),
  ('education-training', 'Education & Training', null, null, 130),
  ('telecommunications', 'Telecommunications', null, null, 140),
  ('media-entertainment', 'Media & Entertainment', null, null, 150),
  ('hospitality-travel', 'Hospitality & Travel', null, null, 160),
  ('agriculture', 'Agriculture', null, null, 170),
  ('automotive', 'Automotive', null, null, 180),
  ('chemicals-materials', 'Chemicals & Materials', null, null, 190),
  ('government-public-sector', 'Government & Public Sector', null, null, 200),
  ('nonprofit-associations', 'Nonprofit & Associations', null, null, 210);

-- depth 1
insert into industries (slug, name, description, parent_id, sort_order) values
  ('b2b-saas', 'B2B SaaS', null, (select id from industries where slug = 'software-technology'), 0),
  ('enterprise-software', 'Enterprise Software', null, (select id from industries where slug = 'software-technology'), 10),
  ('cybersecurity', 'Cybersecurity', null, (select id from industries where slug = 'software-technology'), 20),
  ('data-analytics', 'Data & Analytics', null, (select id from industries where slug = 'software-technology'), 30),
  ('developer-tools', 'Developer Tools & Infrastructure', null, (select id from industries where slug = 'software-technology'), 40),
  ('it-services', 'IT Services & Managed IT', null, (select id from industries where slug = 'software-technology'), 50),
  ('hardware-devices', 'Hardware & Devices', null, (select id from industries where slug = 'software-technology'), 60),
  ('artificial-intelligence', 'AI & Machine Learning', null, (select id from industries where slug = 'software-technology'), 70),
  ('medical-devices', 'Medical Devices', null, (select id from industries where slug = 'healthcare-life-sciences'), 0),
  ('pharmaceuticals', 'Pharmaceuticals', null, (select id from industries where slug = 'healthcare-life-sciences'), 10),
  ('biotechnology', 'Biotechnology', null, (select id from industries where slug = 'healthcare-life-sciences'), 20),
  ('health-it', 'Health IT & Digital Health', null, (select id from industries where slug = 'healthcare-life-sciences'), 30),
  ('dental', 'Dental', null, (select id from industries where slug = 'healthcare-life-sciences'), 40),
  ('veterinary', 'Veterinary', null, (select id from industries where slug = 'healthcare-life-sciences'), 50),
  ('laboratory-diagnostics', 'Laboratory & Diagnostics', null, (select id from industries where slug = 'healthcare-life-sciences'), 60),
  ('long-term-care', 'Long-Term & Senior Care', null, (select id from industries where slug = 'healthcare-life-sciences'), 70),
  ('banking', 'Banking', null, (select id from industries where slug = 'financial-services'), 0),
  ('wealth-management', 'Wealth & Asset Management', null, (select id from industries where slug = 'financial-services'), 10),
  ('payments', 'Payments & Merchant Services', null, (select id from industries where slug = 'financial-services'), 20),
  ('lending', 'Lending & Credit', null, (select id from industries where slug = 'financial-services'), 30),
  ('fintech', 'Fintech', null, (select id from industries where slug = 'financial-services'), 40),
  ('accounting-tax', 'Accounting & Tax', null, (select id from industries where slug = 'financial-services'), 50),
  ('property-casualty', 'Property & Casualty', null, (select id from industries where slug = 'insurance'), 0),
  ('life-insurance', 'Life Insurance', null, (select id from industries where slug = 'insurance'), 10),
  ('health-benefits', 'Health & Employee Benefits', null, (select id from industries where slug = 'insurance'), 20),
  ('commercial-insurance', 'Commercial Lines', null, (select id from industries where slug = 'insurance'), 30),
  ('reinsurance', 'Reinsurance', null, (select id from industries where slug = 'insurance'), 40),
  ('industrial-equipment', 'Industrial Equipment & Machinery', null, (select id from industries where slug = 'manufacturing-industrial'), 0),
  ('automation-robotics', 'Automation & Robotics', null, (select id from industries where slug = 'manufacturing-industrial'), 10),
  ('electronics-components', 'Electronics & Components', null, (select id from industries where slug = 'manufacturing-industrial'), 20),
  ('packaging', 'Packaging', null, (select id from industries where slug = 'manufacturing-industrial'), 30),
  ('metals-fabrication', 'Metals & Fabrication', null, (select id from industries where slug = 'manufacturing-industrial'), 40),
  ('plastics-rubber', 'Plastics & Rubber', null, (select id from industries where slug = 'manufacturing-industrial'), 50),
  ('contract-manufacturing', 'Contract Manufacturing', null, (select id from industries where slug = 'manufacturing-industrial'), 60),
  ('building-materials', 'Building Materials', null, (select id from industries where slug = 'construction-building'), 0),
  ('hvac-plumbing', 'HVAC, Plumbing & Electrical', null, (select id from industries where slug = 'construction-building'), 10),
  ('commercial-construction', 'Commercial Construction', null, (select id from industries where slug = 'construction-building'), 20),
  ('residential-construction', 'Residential Construction', null, (select id from industries where slug = 'construction-building'), 30),
  ('architecture-engineering', 'Architecture & Engineering', null, (select id from industries where slug = 'construction-building'), 40),
  ('heavy-equipment', 'Heavy Equipment & Rental', null, (select id from industries where slug = 'construction-building'), 50),
  ('apparel-accessories', 'Apparel & Accessories', null, (select id from industries where slug = 'consumer-goods-retail'), 0),
  ('home-goods', 'Home & Furniture', null, (select id from industries where slug = 'consumer-goods-retail'), 10),
  ('health-beauty', 'Health & Beauty', null, (select id from industries where slug = 'consumer-goods-retail'), 20),
  ('sporting-goods', 'Sporting Goods & Outdoor', null, (select id from industries where slug = 'consumer-goods-retail'), 30),
  ('toys-games', 'Toys & Games', null, (select id from industries where slug = 'consumer-goods-retail'), 40),
  ('ecommerce-retail', 'E-commerce & Retail Technology', null, (select id from industries where slug = 'consumer-goods-retail'), 50),
  ('food-manufacturing', 'Food Manufacturing', null, (select id from industries where slug = 'food-beverage'), 0),
  ('foodservice-distribution', 'Foodservice & Distribution', null, (select id from industries where slug = 'food-beverage'), 10),
  ('beverages', 'Beverages', null, (select id from industries where slug = 'food-beverage'), 20),
  ('alcohol-spirits', 'Beer, Wine & Spirits', null, (select id from industries where slug = 'food-beverage'), 30),
  ('restaurant-technology', 'Restaurant Technology & Supply', null, (select id from industries where slug = 'food-beverage'), 40),
  ('agriculture-inputs', 'Agricultural Inputs', null, (select id from industries where slug = 'food-beverage'), 50),
  ('oil-gas', 'Oil & Gas', null, (select id from industries where slug = 'energy-utilities'), 0),
  ('renewable-energy', 'Renewable Energy', null, (select id from industries where slug = 'energy-utilities'), 10),
  ('solar', 'Solar', null, (select id from industries where slug = 'energy-utilities'), 20),
  ('utilities', 'Utilities & Grid', null, (select id from industries where slug = 'energy-utilities'), 30),
  ('energy-efficiency', 'Energy Efficiency & Management', null, (select id from industries where slug = 'energy-utilities'), 40),
  ('freight-brokerage', 'Freight & Brokerage', null, (select id from industries where slug = 'transportation-logistics'), 0),
  ('trucking', 'Trucking & Fleet', null, (select id from industries where slug = 'transportation-logistics'), 10),
  ('warehousing', 'Warehousing & Fulfilment', null, (select id from industries where slug = 'transportation-logistics'), 20),
  ('supply-chain-software', 'Supply Chain Software', null, (select id from industries where slug = 'transportation-logistics'), 30),
  ('shipping-maritime', 'Shipping & Maritime', null, (select id from industries where slug = 'transportation-logistics'), 40),
  ('aviation-aerospace', 'Aviation & Aerospace', null, (select id from industries where slug = 'transportation-logistics'), 50),
  ('commercial-real-estate', 'Commercial Real Estate', null, (select id from industries where slug = 'real-estate-property'), 0),
  ('residential-real-estate', 'Residential Real Estate', null, (select id from industries where slug = 'real-estate-property'), 10),
  ('property-management', 'Property Management', null, (select id from industries where slug = 'real-estate-property'), 20),
  ('proptech', 'PropTech', null, (select id from industries where slug = 'real-estate-property'), 30),
  ('facilities-services', 'Facilities & Building Services', null, (select id from industries where slug = 'real-estate-property'), 40),
  ('management-consulting', 'Management Consulting', null, (select id from industries where slug = 'professional-services'), 0),
  ('legal-services', 'Legal Services', null, (select id from industries where slug = 'professional-services'), 10),
  ('staffing-recruiting', 'Staffing & Recruiting', null, (select id from industries where slug = 'professional-services'), 20),
  ('hr-payroll', 'HR, Payroll & PEO', null, (select id from industries where slug = 'professional-services'), 30),
  ('outsourcing-bpo', 'Outsourcing & BPO', null, (select id from industries where slug = 'professional-services'), 40),
  ('digital-marketing', 'Digital Marketing & Agencies', null, (select id from industries where slug = 'marketing-advertising'), 0),
  ('martech', 'Marketing Technology', null, (select id from industries where slug = 'marketing-advertising'), 10),
  ('print-promotional', 'Print & Promotional Products', null, (select id from industries where slug = 'marketing-advertising'), 20),
  ('events-experiential', 'Events & Experiential', null, (select id from industries where slug = 'marketing-advertising'), 30),
  ('market-research', 'Market Research & Insights', null, (select id from industries where slug = 'marketing-advertising'), 40),
  ('k12-education', 'K-12 Education', null, (select id from industries where slug = 'education-training'), 0),
  ('higher-education', 'Higher Education', null, (select id from industries where slug = 'education-training'), 10),
  ('corporate-training', 'Corporate Training & L&D', null, (select id from industries where slug = 'education-training'), 20),
  ('edtech', 'EdTech', null, (select id from industries where slug = 'education-training'), 30),
  ('certification-licensing', 'Certification & Licensing', null, (select id from industries where slug = 'education-training'), 40),
  ('wireless-mobile', 'Wireless & Mobile', null, (select id from industries where slug = 'telecommunications'), 0),
  ('broadband-fiber', 'Broadband & Fiber', null, (select id from industries where slug = 'telecommunications'), 10),
  ('unified-communications', 'Unified Communications & VoIP', null, (select id from industries where slug = 'telecommunications'), 20),
  ('network-infrastructure', 'Network Infrastructure', null, (select id from industries where slug = 'telecommunications'), 30),
  ('data-centers', 'Data Centers & Colocation', null, (select id from industries where slug = 'telecommunications'), 40),
  ('broadcast-streaming', 'Broadcast & Streaming', null, (select id from industries where slug = 'media-entertainment'), 0),
  ('publishing', 'Publishing', null, (select id from industries where slug = 'media-entertainment'), 10),
  ('music-audio', 'Music & Audio', null, (select id from industries where slug = 'media-entertainment'), 20),
  ('gaming-esports', 'Gaming & Esports', null, (select id from industries where slug = 'media-entertainment'), 30),
  ('sports-teams', 'Sports & Teams', null, (select id from industries where slug = 'media-entertainment'), 40),
  ('hotels-lodging', 'Hotels & Lodging', null, (select id from industries where slug = 'hospitality-travel'), 0),
  ('restaurants', 'Restaurants & Bars', null, (select id from industries where slug = 'hospitality-travel'), 10),
  ('travel-tourism', 'Travel & Tourism', null, (select id from industries where slug = 'hospitality-travel'), 20),
  ('hospitality-technology', 'Hospitality Technology', null, (select id from industries where slug = 'hospitality-travel'), 30),
  ('catering-events', 'Catering & Venues', null, (select id from industries where slug = 'hospitality-travel'), 40),
  ('crop-production', 'Crop Production', null, (select id from industries where slug = 'agriculture'), 0),
  ('livestock', 'Livestock & Animal Health', null, (select id from industries where slug = 'agriculture'), 10),
  ('agtech', 'AgTech & Precision Agriculture', null, (select id from industries where slug = 'agriculture'), 20),
  ('farm-equipment', 'Farm Equipment', null, (select id from industries where slug = 'agriculture'), 30),
  ('forestry', 'Forestry & Timber', null, (select id from industries where slug = 'agriculture'), 40),
  ('auto-dealers', 'Dealers & Dealer Services', null, (select id from industries where slug = 'automotive'), 0),
  ('auto-parts', 'Parts & Aftermarket', null, (select id from industries where slug = 'automotive'), 10),
  ('fleet-services', 'Fleet & Commercial Vehicles', null, (select id from industries where slug = 'automotive'), 20),
  ('electric-vehicles', 'Electric Vehicles & Charging', null, (select id from industries where slug = 'automotive'), 30),
  ('auto-technology', 'Automotive Technology', null, (select id from industries where slug = 'automotive'), 40),
  ('specialty-chemicals', 'Specialty Chemicals', null, (select id from industries where slug = 'chemicals-materials'), 0),
  ('industrial-gases', 'Industrial Gases', null, (select id from industries where slug = 'chemicals-materials'), 10),
  ('coatings-adhesives', 'Coatings & Adhesives', null, (select id from industries where slug = 'chemicals-materials'), 20),
  ('advanced-materials', 'Advanced Materials & Composites', null, (select id from industries where slug = 'chemicals-materials'), 30),
  ('federal-government', 'Federal / National Government', null, (select id from industries where slug = 'government-public-sector'), 0),
  ('state-local-government', 'State, Provincial & Local Government', null, (select id from industries where slug = 'government-public-sector'), 10),
  ('defense-security', 'Defense & National Security', null, (select id from industries where slug = 'government-public-sector'), 20),
  ('public-safety', 'Public Safety & Emergency Services', null, (select id from industries where slug = 'government-public-sector'), 30),
  ('charities-foundations', 'Charities & Foundations', null, (select id from industries where slug = 'nonprofit-associations'), 0),
  ('trade-associations', 'Trade & Professional Associations', null, (select id from industries where slug = 'nonprofit-associations'), 10),
  ('faith-based', 'Faith-Based Organisations', null, (select id from industries where slug = 'nonprofit-associations'), 20),
  ('membership-organisations', 'Membership Organisations', null, (select id from industries where slug = 'nonprofit-associations'), 30);

-- product_categories: 68 entries
-- depth 0
insert into product_categories (slug, name, description, parent_id, sort_order) values
  ('software-subscriptions', 'Software & Subscriptions', null, null, 0),
  ('capital-equipment', 'Capital Equipment', 'High-value assets with long cycles, financing and committee approval.', null, 10),
  ('hardware-devices-products', 'Hardware & Devices', null, null, 20),
  ('consumables-supplies', 'Consumables & Supplies', 'Repeat-purchase products where the sale is recurring by nature.', null, 30),
  ('professional-services-sold', 'Professional Services', null, null, 40),
  ('managed-recurring-services', 'Managed & Recurring Services', null, null, 50),
  ('financial-products', 'Financial & Insurance Products', null, null, 60),
  ('media-advertising-inventory', 'Media & Advertising', null, null, 70),
  ('training-certification', 'Training & Certification', null, null, 80),
  ('memberships-licensing', 'Memberships & Licensing', null, null, 90),
  ('raw-materials', 'Raw Materials & Commodities', null, null, 100),
  ('construction-building-products', 'Construction & Building Products', null, null, 110);

-- depth 1
insert into product_categories (slug, name, description, parent_id, sort_order) values
  ('saas-platform', 'SaaS Platform', null, (select id from product_categories where slug = 'software-subscriptions'), 0),
  ('enterprise-license', 'Enterprise Licence', null, (select id from product_categories where slug = 'software-subscriptions'), 10),
  ('mobile-applications', 'Mobile Applications', null, (select id from product_categories where slug = 'software-subscriptions'), 20),
  ('api-usage-based', 'API & Usage-Based Products', null, (select id from product_categories where slug = 'software-subscriptions'), 30),
  ('marketplace-platform', 'Marketplace & Platform Fees', null, (select id from product_categories where slug = 'software-subscriptions'), 40),
  ('production-machinery', 'Production Machinery', null, (select id from product_categories where slug = 'capital-equipment'), 0),
  ('medical-capital-equipment', 'Medical Capital Equipment', null, (select id from product_categories where slug = 'capital-equipment'), 10),
  ('vehicles-fleet', 'Vehicles & Fleet', null, (select id from product_categories where slug = 'capital-equipment'), 20),
  ('construction-equipment', 'Construction Equipment', null, (select id from product_categories where slug = 'capital-equipment'), 30),
  ('laboratory-instruments', 'Laboratory Instruments', null, (select id from product_categories where slug = 'capital-equipment'), 40),
  ('computing-hardware', 'Computing Hardware', null, (select id from product_categories where slug = 'hardware-devices-products'), 0),
  ('networking-equipment', 'Networking Equipment', null, (select id from product_categories where slug = 'hardware-devices-products'), 10),
  ('sensors-iot', 'Sensors & IoT Devices', null, (select id from product_categories where slug = 'hardware-devices-products'), 20),
  ('consumer-electronics', 'Consumer Electronics', null, (select id from product_categories where slug = 'hardware-devices-products'), 30),
  ('components-parts', 'Components & Parts', null, (select id from product_categories where slug = 'hardware-devices-products'), 40),
  ('medical-supplies', 'Medical & Surgical Supplies', null, (select id from product_categories where slug = 'consumables-supplies'), 0),
  ('industrial-consumables', 'Industrial Consumables', null, (select id from product_categories where slug = 'consumables-supplies'), 10),
  ('office-facility-supplies', 'Office & Facility Supplies', null, (select id from product_categories where slug = 'consumables-supplies'), 20),
  ('food-ingredients', 'Food & Ingredients', null, (select id from product_categories where slug = 'consumables-supplies'), 30),
  ('chemicals-lubricants', 'Chemicals & Lubricants', null, (select id from product_categories where slug = 'consumables-supplies'), 40),
  ('consulting-engagements', 'Consulting Engagements', null, (select id from product_categories where slug = 'professional-services-sold'), 0),
  ('implementation-integration', 'Implementation & Integration', null, (select id from product_categories where slug = 'professional-services-sold'), 10),
  ('design-creative', 'Design & Creative Services', null, (select id from product_categories where slug = 'professional-services-sold'), 20),
  ('legal-financial-services', 'Legal & Financial Services', null, (select id from product_categories where slug = 'professional-services-sold'), 30),
  ('staffing-placement', 'Staffing & Placement', null, (select id from product_categories where slug = 'professional-services-sold'), 40),
  ('managed-it-services', 'Managed IT & Security', null, (select id from product_categories where slug = 'managed-recurring-services'), 0),
  ('maintenance-contracts', 'Maintenance & Support Contracts', null, (select id from product_categories where slug = 'managed-recurring-services'), 10),
  ('facilities-management', 'Facilities Management', null, (select id from product_categories where slug = 'managed-recurring-services'), 20),
  ('logistics-services', 'Logistics & Fulfilment Services', null, (select id from product_categories where slug = 'managed-recurring-services'), 30),
  ('bpo-services', 'Outsourced Operations', null, (select id from product_categories where slug = 'managed-recurring-services'), 40),
  ('lending-products', 'Loans & Credit Products', null, (select id from product_categories where slug = 'financial-products'), 0),
  ('payment-processing', 'Payment Processing', null, (select id from product_categories where slug = 'financial-products'), 10),
  ('insurance-policies', 'Insurance Policies', null, (select id from product_categories where slug = 'financial-products'), 20),
  ('investment-products', 'Investment Products', null, (select id from product_categories where slug = 'financial-products'), 30),
  ('employee-benefits-products', 'Employee Benefits', null, (select id from product_categories where slug = 'financial-products'), 40),
  ('digital-advertising', 'Digital Advertising', null, (select id from product_categories where slug = 'media-advertising-inventory'), 0),
  ('print-broadcast-advertising', 'Print & Broadcast Advertising', null, (select id from product_categories where slug = 'media-advertising-inventory'), 10),
  ('sponsorships', 'Sponsorships & Partnerships', null, (select id from product_categories where slug = 'media-advertising-inventory'), 20),
  ('event-exhibition-space', 'Event & Exhibition Space', null, (select id from product_categories where slug = 'media-advertising-inventory'), 30),
  ('corporate-training-programs', 'Corporate Training Programmes', null, (select id from product_categories where slug = 'training-certification'), 0),
  ('online-courses', 'Online Courses & Curriculum', null, (select id from product_categories where slug = 'training-certification'), 10),
  ('certification-programs', 'Certification Programmes', null, (select id from product_categories where slug = 'training-certification'), 20),
  ('membership-subscriptions', 'Memberships & Dues', null, (select id from product_categories where slug = 'memberships-licensing'), 0),
  ('ip-licensing', 'IP & Brand Licensing', null, (select id from product_categories where slug = 'memberships-licensing'), 10),
  ('franchise-opportunities', 'Franchise Opportunities', null, (select id from product_categories where slug = 'memberships-licensing'), 20),
  ('data-licensing', 'Data & Content Licensing', null, (select id from product_categories where slug = 'memberships-licensing'), 30),
  ('metals-minerals', 'Metals & Minerals', null, (select id from product_categories where slug = 'raw-materials'), 0),
  ('plastics-polymers', 'Plastics & Polymers', null, (select id from product_categories where slug = 'raw-materials'), 10),
  ('agricultural-commodities', 'Agricultural Commodities', null, (select id from product_categories where slug = 'raw-materials'), 20),
  ('energy-commodities', 'Energy Commodities', null, (select id from product_categories where slug = 'raw-materials'), 30),
  ('textiles-fabrics', 'Textiles & Fabrics', null, (select id from product_categories where slug = 'raw-materials'), 40),
  ('structural-materials', 'Structural Materials', null, (select id from product_categories where slug = 'construction-building-products'), 0),
  ('interior-finishes', 'Interior Finishes', null, (select id from product_categories where slug = 'construction-building-products'), 10),
  ('mechanical-systems', 'HVAC & Mechanical Systems', null, (select id from product_categories where slug = 'construction-building-products'), 20),
  ('electrical-lighting', 'Electrical & Lighting', null, (select id from product_categories where slug = 'construction-building-products'), 30),
  ('tools-hardware', 'Tools & Hardware', null, (select id from product_categories where slug = 'construction-building-products'), 40);

-- depth 0: the root — "Anywhere / Fully Remote", ancestor of everything
insert into territories (slug, name, kind, sort_order) values
  ('anywhere', 'Anywhere / Fully Remote', 'global', 0);

-- depth 1: countries. Selecting one of these means "nationwide".
insert into territories (slug, name, kind, iso_code, parent_id, sort_order) values
  ('united-states', 'United States (Nationwide)', 'country', 'US', (select id from territories where slug = 'anywhere'), 0),
  ('canada', 'Canada (Nationwide)', 'country', 'CA', (select id from territories where slug = 'anywhere'), 10);

-- depth 2: regions
insert into territories (slug, name, kind, parent_id, sort_order) values
  ('us-northeast', 'Northeast', 'region', (select id from territories where slug = 'united-states'), 0),
  ('us-midwest', 'Midwest', 'region', (select id from territories where slug = 'united-states'), 10),
  ('us-south', 'South', 'region', (select id from territories where slug = 'united-states'), 20),
  ('us-west', 'West', 'region', (select id from territories where slug = 'united-states'), 30),
  ('ca-atlantic', 'Atlantic Canada', 'region', (select id from territories where slug = 'canada'), 40),
  ('ca-central', 'Central Canada', 'region', (select id from territories where slug = 'canada'), 50),
  ('ca-prairies', 'Prairie Provinces', 'region', (select id from territories where slug = 'canada'), 60),
  ('ca-west-coast', 'West Coast', 'region', (select id from territories where slug = 'canada'), 70),
  ('ca-north', 'Northern Canada', 'region', (select id from territories where slug = 'canada'), 80);

-- depth 3: states, districts, provinces and territories
insert into territories (slug, name, kind, subdivision_type, iso_code, parent_id, sort_order) values
  ('connecticut', 'Connecticut', 'subdivision', 'State', 'CT', (select id from territories where slug = 'us-northeast'), 0),
  ('maine', 'Maine', 'subdivision', 'State', 'ME', (select id from territories where slug = 'us-northeast'), 10),
  ('massachusetts', 'Massachusetts', 'subdivision', 'State', 'MA', (select id from territories where slug = 'us-northeast'), 20),
  ('new-hampshire', 'New Hampshire', 'subdivision', 'State', 'NH', (select id from territories where slug = 'us-northeast'), 30),
  ('rhode-island', 'Rhode Island', 'subdivision', 'State', 'RI', (select id from territories where slug = 'us-northeast'), 40),
  ('vermont', 'Vermont', 'subdivision', 'State', 'VT', (select id from territories where slug = 'us-northeast'), 50),
  ('new-jersey', 'New Jersey', 'subdivision', 'State', 'NJ', (select id from territories where slug = 'us-northeast'), 60),
  ('new-york', 'New York', 'subdivision', 'State', 'NY', (select id from territories where slug = 'us-northeast'), 70),
  ('pennsylvania', 'Pennsylvania', 'subdivision', 'State', 'PA', (select id from territories where slug = 'us-northeast'), 80),
  ('illinois', 'Illinois', 'subdivision', 'State', 'IL', (select id from territories where slug = 'us-midwest'), 90),
  ('indiana', 'Indiana', 'subdivision', 'State', 'IN', (select id from territories where slug = 'us-midwest'), 100),
  ('michigan', 'Michigan', 'subdivision', 'State', 'MI', (select id from territories where slug = 'us-midwest'), 110),
  ('ohio', 'Ohio', 'subdivision', 'State', 'OH', (select id from territories where slug = 'us-midwest'), 120),
  ('wisconsin', 'Wisconsin', 'subdivision', 'State', 'WI', (select id from territories where slug = 'us-midwest'), 130),
  ('iowa', 'Iowa', 'subdivision', 'State', 'IA', (select id from territories where slug = 'us-midwest'), 140),
  ('kansas', 'Kansas', 'subdivision', 'State', 'KS', (select id from territories where slug = 'us-midwest'), 150),
  ('minnesota', 'Minnesota', 'subdivision', 'State', 'MN', (select id from territories where slug = 'us-midwest'), 160),
  ('missouri', 'Missouri', 'subdivision', 'State', 'MO', (select id from territories where slug = 'us-midwest'), 170),
  ('nebraska', 'Nebraska', 'subdivision', 'State', 'NE', (select id from territories where slug = 'us-midwest'), 180),
  ('north-dakota', 'North Dakota', 'subdivision', 'State', 'ND', (select id from territories where slug = 'us-midwest'), 190),
  ('south-dakota', 'South Dakota', 'subdivision', 'State', 'SD', (select id from territories where slug = 'us-midwest'), 200),
  ('delaware', 'Delaware', 'subdivision', 'State', 'DE', (select id from territories where slug = 'us-south'), 210),
  ('district-of-columbia', 'District of Columbia', 'subdivision', 'District', 'DC', (select id from territories where slug = 'us-south'), 220),
  ('florida', 'Florida', 'subdivision', 'State', 'FL', (select id from territories where slug = 'us-south'), 230),
  ('georgia', 'Georgia', 'subdivision', 'State', 'GA', (select id from territories where slug = 'us-south'), 240),
  ('maryland', 'Maryland', 'subdivision', 'State', 'MD', (select id from territories where slug = 'us-south'), 250),
  ('north-carolina', 'North Carolina', 'subdivision', 'State', 'NC', (select id from territories where slug = 'us-south'), 260),
  ('south-carolina', 'South Carolina', 'subdivision', 'State', 'SC', (select id from territories where slug = 'us-south'), 270),
  ('virginia', 'Virginia', 'subdivision', 'State', 'VA', (select id from territories where slug = 'us-south'), 280),
  ('west-virginia', 'West Virginia', 'subdivision', 'State', 'WV', (select id from territories where slug = 'us-south'), 290),
  ('alabama', 'Alabama', 'subdivision', 'State', 'AL', (select id from territories where slug = 'us-south'), 300),
  ('kentucky', 'Kentucky', 'subdivision', 'State', 'KY', (select id from territories where slug = 'us-south'), 310),
  ('mississippi', 'Mississippi', 'subdivision', 'State', 'MS', (select id from territories where slug = 'us-south'), 320),
  ('tennessee', 'Tennessee', 'subdivision', 'State', 'TN', (select id from territories where slug = 'us-south'), 330),
  ('arkansas', 'Arkansas', 'subdivision', 'State', 'AR', (select id from territories where slug = 'us-south'), 340),
  ('louisiana', 'Louisiana', 'subdivision', 'State', 'LA', (select id from territories where slug = 'us-south'), 350),
  ('oklahoma', 'Oklahoma', 'subdivision', 'State', 'OK', (select id from territories where slug = 'us-south'), 360),
  ('texas', 'Texas', 'subdivision', 'State', 'TX', (select id from territories where slug = 'us-south'), 370),
  ('arizona', 'Arizona', 'subdivision', 'State', 'AZ', (select id from territories where slug = 'us-west'), 380),
  ('colorado', 'Colorado', 'subdivision', 'State', 'CO', (select id from territories where slug = 'us-west'), 390),
  ('idaho', 'Idaho', 'subdivision', 'State', 'ID', (select id from territories where slug = 'us-west'), 400),
  ('montana', 'Montana', 'subdivision', 'State', 'MT', (select id from territories where slug = 'us-west'), 410),
  ('nevada', 'Nevada', 'subdivision', 'State', 'NV', (select id from territories where slug = 'us-west'), 420),
  ('new-mexico', 'New Mexico', 'subdivision', 'State', 'NM', (select id from territories where slug = 'us-west'), 430),
  ('utah', 'Utah', 'subdivision', 'State', 'UT', (select id from territories where slug = 'us-west'), 440),
  ('wyoming', 'Wyoming', 'subdivision', 'State', 'WY', (select id from territories where slug = 'us-west'), 450),
  ('alaska', 'Alaska', 'subdivision', 'State', 'AK', (select id from territories where slug = 'us-west'), 460),
  ('california', 'California', 'subdivision', 'State', 'CA', (select id from territories where slug = 'us-west'), 470),
  ('hawaii', 'Hawaii', 'subdivision', 'State', 'HI', (select id from territories where slug = 'us-west'), 480),
  ('oregon', 'Oregon', 'subdivision', 'State', 'OR', (select id from territories where slug = 'us-west'), 490),
  ('washington', 'Washington', 'subdivision', 'State', 'WA', (select id from territories where slug = 'us-west'), 500),
  ('newfoundland-and-labrador', 'Newfoundland and Labrador', 'subdivision', 'Province', 'NL', (select id from territories where slug = 'ca-atlantic'), 510),
  ('prince-edward-island', 'Prince Edward Island', 'subdivision', 'Province', 'PE', (select id from territories where slug = 'ca-atlantic'), 520),
  ('nova-scotia', 'Nova Scotia', 'subdivision', 'Province', 'NS', (select id from territories where slug = 'ca-atlantic'), 530),
  ('new-brunswick', 'New Brunswick', 'subdivision', 'Province', 'NB', (select id from territories where slug = 'ca-atlantic'), 540),
  ('quebec', 'Quebec', 'subdivision', 'Province', 'QC', (select id from territories where slug = 'ca-central'), 550),
  ('ontario', 'Ontario', 'subdivision', 'Province', 'ON', (select id from territories where slug = 'ca-central'), 560),
  ('manitoba', 'Manitoba', 'subdivision', 'Province', 'MB', (select id from territories where slug = 'ca-prairies'), 570),
  ('saskatchewan', 'Saskatchewan', 'subdivision', 'Province', 'SK', (select id from territories where slug = 'ca-prairies'), 580),
  ('alberta', 'Alberta', 'subdivision', 'Province', 'AB', (select id from territories where slug = 'ca-prairies'), 590),
  ('british-columbia', 'British Columbia', 'subdivision', 'Province', 'BC', (select id from territories where slug = 'ca-west-coast'), 600),
  ('yukon', 'Yukon', 'subdivision', 'Territory', 'YT', (select id from territories where slug = 'ca-north'), 610),
  ('northwest-territories', 'Northwest Territories', 'subdivision', 'Territory', 'NT', (select id from territories where slug = 'ca-north'), 620),
  ('nunavut', 'Nunavut', 'subdivision', 'Territory', 'NU', (select id from territories where slug = 'ca-north'), 630);

-- depth 4: metropolitan areas
insert into territories (slug, name, kind, parent_id, sort_order) values
  ('new-york-metro', 'New York Metro', 'metro', (select id from territories where slug = 'new-york'), 0),
  ('buffalo-ny', 'Buffalo', 'metro', (select id from territories where slug = 'new-york'), 10),
  ('rochester-ny', 'Rochester', 'metro', (select id from territories where slug = 'new-york'), 20),
  ('albany-ny', 'Albany', 'metro', (select id from territories where slug = 'new-york'), 30),
  ('syracuse-ny', 'Syracuse', 'metro', (select id from territories where slug = 'new-york'), 40),
  ('los-angeles-metro', 'Los Angeles Metro', 'metro', (select id from territories where slug = 'california'), 50),
  ('san-francisco-bay-area', 'San Francisco Bay Area', 'metro', (select id from territories where slug = 'california'), 60),
  ('san-diego-ca', 'San Diego', 'metro', (select id from territories where slug = 'california'), 70),
  ('sacramento-ca', 'Sacramento', 'metro', (select id from territories where slug = 'california'), 80),
  ('riverside-ca', 'Inland Empire', 'metro', (select id from territories where slug = 'california'), 90),
  ('san-jose-ca', 'San Jose & Silicon Valley', 'metro', (select id from territories where slug = 'california'), 100),
  ('fresno-ca', 'Fresno', 'metro', (select id from territories where slug = 'california'), 110),
  ('bakersfield-ca', 'Bakersfield', 'metro', (select id from territories where slug = 'california'), 120),
  ('oxnard-ca', 'Oxnard & Ventura County', 'metro', (select id from territories where slug = 'california'), 130),
  ('stockton-ca', 'Stockton', 'metro', (select id from territories where slug = 'california'), 140),
  ('chicago-il', 'Chicago Metro', 'metro', (select id from territories where slug = 'illinois'), 150),
  ('dallas-fort-worth-tx', 'Dallas–Fort Worth', 'metro', (select id from territories where slug = 'texas'), 160),
  ('houston-tx', 'Houston', 'metro', (select id from territories where slug = 'texas'), 170),
  ('san-antonio-tx', 'San Antonio', 'metro', (select id from territories where slug = 'texas'), 180),
  ('austin-tx', 'Austin', 'metro', (select id from territories where slug = 'texas'), 190),
  ('el-paso-tx', 'El Paso', 'metro', (select id from territories where slug = 'texas'), 200),
  ('mcallen-tx', 'McAllen & Rio Grande Valley', 'metro', (select id from territories where slug = 'texas'), 210),
  ('washington-dc-metro', 'Washington DC Metro', 'metro', (select id from territories where slug = 'district-of-columbia'), 220),
  ('philadelphia-pa', 'Philadelphia Metro', 'metro', (select id from territories where slug = 'pennsylvania'), 230),
  ('pittsburgh-pa', 'Pittsburgh', 'metro', (select id from territories where slug = 'pennsylvania'), 240),
  ('harrisburg-pa', 'Harrisburg', 'metro', (select id from territories where slug = 'pennsylvania'), 250),
  ('allentown-pa', 'Allentown & Lehigh Valley', 'metro', (select id from territories where slug = 'pennsylvania'), 260),
  ('scranton-pa', 'Scranton & Wilkes-Barre', 'metro', (select id from territories where slug = 'pennsylvania'), 270),
  ('miami-fl', 'Miami & South Florida', 'metro', (select id from territories where slug = 'florida'), 280),
  ('tampa-fl', 'Tampa Bay', 'metro', (select id from territories where slug = 'florida'), 290),
  ('orlando-fl', 'Orlando', 'metro', (select id from territories where slug = 'florida'), 300),
  ('jacksonville-fl', 'Jacksonville', 'metro', (select id from territories where slug = 'florida'), 310),
  ('cape-coral-fl', 'Fort Myers & Cape Coral', 'metro', (select id from territories where slug = 'florida'), 320),
  ('north-port-fl', 'Sarasota & North Port', 'metro', (select id from territories where slug = 'florida'), 330),
  ('lakeland-fl', 'Lakeland', 'metro', (select id from territories where slug = 'florida'), 340),
  ('palm-bay-fl', 'Palm Bay & Melbourne', 'metro', (select id from territories where slug = 'florida'), 350),
  ('deltona-fl', 'Daytona Beach & Deltona', 'metro', (select id from territories where slug = 'florida'), 360),
  ('atlanta-ga', 'Atlanta Metro', 'metro', (select id from territories where slug = 'georgia'), 370),
  ('augusta-ga', 'Augusta', 'metro', (select id from territories where slug = 'georgia'), 380),
  ('boston-ma', 'Greater Boston', 'metro', (select id from territories where slug = 'massachusetts'), 390),
  ('worcester-ma', 'Worcester', 'metro', (select id from territories where slug = 'massachusetts'), 400),
  ('springfield-ma', 'Springfield', 'metro', (select id from territories where slug = 'massachusetts'), 410),
  ('phoenix-az', 'Phoenix Metro', 'metro', (select id from territories where slug = 'arizona'), 420),
  ('tucson-az', 'Tucson', 'metro', (select id from territories where slug = 'arizona'), 430),
  ('detroit-mi', 'Detroit Metro', 'metro', (select id from territories where slug = 'michigan'), 440),
  ('grand-rapids-mi', 'Grand Rapids', 'metro', (select id from territories where slug = 'michigan'), 450),
  ('seattle-wa', 'Seattle Metro', 'metro', (select id from territories where slug = 'washington'), 460),
  ('spokane-wa', 'Spokane', 'metro', (select id from territories where slug = 'washington'), 470),
  ('minneapolis-mn', 'Minneapolis–St. Paul', 'metro', (select id from territories where slug = 'minnesota'), 480),
  ('denver-co', 'Denver Metro', 'metro', (select id from territories where slug = 'colorado'), 490),
  ('colorado-springs-co', 'Colorado Springs', 'metro', (select id from territories where slug = 'colorado'), 500),
  ('baltimore-md', 'Baltimore', 'metro', (select id from territories where slug = 'maryland'), 510),
  ('st-louis-mo', 'St. Louis', 'metro', (select id from territories where slug = 'missouri'), 520),
  ('kansas-city-mo', 'Kansas City', 'metro', (select id from territories where slug = 'missouri'), 530),
  ('charlotte-nc', 'Charlotte', 'metro', (select id from territories where slug = 'north-carolina'), 540),
  ('raleigh-nc', 'Raleigh & Research Triangle', 'metro', (select id from territories where slug = 'north-carolina'), 550),
  ('greensboro-nc', 'Greensboro & Winston-Salem', 'metro', (select id from territories where slug = 'north-carolina'), 560),
  ('durham-nc', 'Durham & Chapel Hill', 'metro', (select id from territories where slug = 'north-carolina'), 570),
  ('portland-or', 'Portland Metro', 'metro', (select id from territories where slug = 'oregon'), 580),
  ('las-vegas-nv', 'Las Vegas', 'metro', (select id from territories where slug = 'nevada'), 590),
  ('reno-nv', 'Reno', 'metro', (select id from territories where slug = 'nevada'), 600),
  ('cincinnati-oh', 'Cincinnati', 'metro', (select id from territories where slug = 'ohio'), 610),
  ('columbus-oh', 'Columbus', 'metro', (select id from territories where slug = 'ohio'), 620),
  ('cleveland-oh', 'Cleveland', 'metro', (select id from territories where slug = 'ohio'), 630),
  ('dayton-oh', 'Dayton', 'metro', (select id from territories where slug = 'ohio'), 640),
  ('akron-oh', 'Akron', 'metro', (select id from territories where slug = 'ohio'), 650),
  ('toledo-oh', 'Toledo', 'metro', (select id from territories where slug = 'ohio'), 660),
  ('indianapolis-in', 'Indianapolis', 'metro', (select id from territories where slug = 'indiana'), 670),
  ('nashville-tn', 'Nashville', 'metro', (select id from territories where slug = 'tennessee'), 680),
  ('memphis-tn', 'Memphis', 'metro', (select id from territories where slug = 'tennessee'), 690),
  ('knoxville-tn', 'Knoxville', 'metro', (select id from territories where slug = 'tennessee'), 700),
  ('chattanooga-tn', 'Chattanooga', 'metro', (select id from territories where slug = 'tennessee'), 710),
  ('virginia-beach-va', 'Virginia Beach & Hampton Roads', 'metro', (select id from territories where slug = 'virginia'), 720),
  ('richmond-va', 'Richmond', 'metro', (select id from territories where slug = 'virginia'), 730),
  ('providence-ri', 'Providence', 'metro', (select id from territories where slug = 'rhode-island'), 740),
  ('milwaukee-wi', 'Milwaukee', 'metro', (select id from territories where slug = 'wisconsin'), 750),
  ('madison-wi', 'Madison', 'metro', (select id from territories where slug = 'wisconsin'), 760),
  ('oklahoma-city-ok', 'Oklahoma City', 'metro', (select id from territories where slug = 'oklahoma'), 770),
  ('tulsa-ok', 'Tulsa', 'metro', (select id from territories where slug = 'oklahoma'), 780),
  ('louisville-ky', 'Louisville', 'metro', (select id from territories where slug = 'kentucky'), 790),
  ('new-orleans-la', 'New Orleans', 'metro', (select id from territories where slug = 'louisiana'), 800),
  ('baton-rouge-la', 'Baton Rouge', 'metro', (select id from territories where slug = 'louisiana'), 810),
  ('salt-lake-city-ut', 'Salt Lake City', 'metro', (select id from territories where slug = 'utah'), 820),
  ('ogden-ut', 'Ogden', 'metro', (select id from territories where slug = 'utah'), 830),
  ('provo-ut', 'Provo & Utah Valley', 'metro', (select id from territories where slug = 'utah'), 840),
  ('hartford-ct', 'Hartford', 'metro', (select id from territories where slug = 'connecticut'), 850),
  ('bridgeport-ct', 'Bridgeport & Fairfield County', 'metro', (select id from territories where slug = 'connecticut'), 860),
  ('new-haven-ct', 'New Haven', 'metro', (select id from territories where slug = 'connecticut'), 870),
  ('birmingham-al', 'Birmingham', 'metro', (select id from territories where slug = 'alabama'), 880),
  ('huntsville-al', 'Huntsville', 'metro', (select id from territories where slug = 'alabama'), 890),
  ('honolulu-hi', 'Honolulu', 'metro', (select id from territories where slug = 'hawaii'), 900),
  ('omaha-ne', 'Omaha', 'metro', (select id from territories where slug = 'nebraska'), 910),
  ('greenville-sc', 'Greenville & Upstate', 'metro', (select id from territories where slug = 'south-carolina'), 920),
  ('charleston-sc', 'Charleston', 'metro', (select id from territories where slug = 'south-carolina'), 930),
  ('columbia-sc', 'Columbia', 'metro', (select id from territories where slug = 'south-carolina'), 940),
  ('albuquerque-nm', 'Albuquerque', 'metro', (select id from territories where slug = 'new-mexico'), 950),
  ('boise-id', 'Boise', 'metro', (select id from territories where slug = 'idaho'), 960),
  ('little-rock-ar', 'Little Rock', 'metro', (select id from territories where slug = 'arkansas'), 970),
  ('des-moines-ia', 'Des Moines', 'metro', (select id from territories where slug = 'iowa'), 980),
  ('wichita-ks', 'Wichita', 'metro', (select id from territories where slug = 'kansas'), 990),
  ('jackson-ms', 'Jackson', 'metro', (select id from territories where slug = 'mississippi'), 1000),
  ('anchorage-ak', 'Anchorage', 'metro', (select id from territories where slug = 'alaska'), 1010),
  ('portland-me', 'Portland', 'metro', (select id from territories where slug = 'maine'), 1020),
  ('manchester-nh', 'Manchester & Nashua', 'metro', (select id from territories where slug = 'new-hampshire'), 1030),
  ('burlington-vt', 'Burlington', 'metro', (select id from territories where slug = 'vermont'), 1040),
  ('wilmington-de', 'Wilmington', 'metro', (select id from territories where slug = 'delaware'), 1050),
  ('charleston-wv', 'Charleston', 'metro', (select id from territories where slug = 'west-virginia'), 1060),
  ('billings-mt', 'Billings', 'metro', (select id from territories where slug = 'montana'), 1070),
  ('cheyenne-wy', 'Cheyenne', 'metro', (select id from territories where slug = 'wyoming'), 1080),
  ('fargo-nd', 'Fargo', 'metro', (select id from territories where slug = 'north-dakota'), 1090),
  ('sioux-falls-sd', 'Sioux Falls', 'metro', (select id from territories where slug = 'south-dakota'), 1100),
  ('toronto-on', 'Greater Toronto Area', 'metro', (select id from territories where slug = 'ontario'), 1110),
  ('ottawa-on', 'Ottawa', 'metro', (select id from territories where slug = 'ontario'), 1120),
  ('hamilton-on', 'Hamilton', 'metro', (select id from territories where slug = 'ontario'), 1130),
  ('kitchener-on', 'Kitchener–Waterloo', 'metro', (select id from territories where slug = 'ontario'), 1140),
  ('london-on', 'London', 'metro', (select id from territories where slug = 'ontario'), 1150),
  ('windsor-on', 'Windsor', 'metro', (select id from territories where slug = 'ontario'), 1160),
  ('oshawa-on', 'Oshawa & Durham Region', 'metro', (select id from territories where slug = 'ontario'), 1170),
  ('barrie-on', 'Barrie', 'metro', (select id from territories where slug = 'ontario'), 1180),
  ('guelph-on', 'Guelph', 'metro', (select id from territories where slug = 'ontario'), 1190),
  ('montreal-qc', 'Montreal', 'metro', (select id from territories where slug = 'quebec'), 1200),
  ('quebec-city-qc', 'Quebec City', 'metro', (select id from territories where slug = 'quebec'), 1210),
  ('sherbrooke-qc', 'Sherbrooke', 'metro', (select id from territories where slug = 'quebec'), 1220),
  ('gatineau-qc', 'Gatineau', 'metro', (select id from territories where slug = 'quebec'), 1230),
  ('vancouver-bc', 'Metro Vancouver', 'metro', (select id from territories where slug = 'british-columbia'), 1240),
  ('victoria-bc', 'Victoria', 'metro', (select id from territories where slug = 'british-columbia'), 1250),
  ('kelowna-bc', 'Kelowna & Okanagan', 'metro', (select id from territories where slug = 'british-columbia'), 1260),
  ('calgary-ab', 'Calgary', 'metro', (select id from territories where slug = 'alberta'), 1270),
  ('edmonton-ab', 'Edmonton', 'metro', (select id from territories where slug = 'alberta'), 1280),
  ('winnipeg-mb', 'Winnipeg', 'metro', (select id from territories where slug = 'manitoba'), 1290),
  ('saskatoon-sk', 'Saskatoon', 'metro', (select id from territories where slug = 'saskatchewan'), 1300),
  ('regina-sk', 'Regina', 'metro', (select id from territories where slug = 'saskatchewan'), 1310),
  ('halifax-ns', 'Halifax', 'metro', (select id from territories where slug = 'nova-scotia'), 1320),
  ('moncton-nb', 'Moncton', 'metro', (select id from territories where slug = 'new-brunswick'), 1330),
  ('st-johns-nl', 'St. John''s', 'metro', (select id from territories where slug = 'newfoundland-and-labrador'), 1340);

-- customer_types: 8 entries
insert into customer_types (slug, name, description, sort_order) values
  ('smb', 'Small Business', 'Roughly 1–50 employees. Short cycles, owner is usually the buyer.', 0),
  ('mid-market', 'Mid-Market', 'Roughly 51–1,000 employees. Committee buying, defined procurement.', 10),
  ('enterprise', 'Enterprise', '1,000+ employees. Long cycles, multiple stakeholders, formal RFPs.', 20),
  ('government', 'Government & Public Sector', 'Federal, state, provincial and municipal. Procurement rules apply.', 30),
  ('healthcare-providers', 'Healthcare Providers & Systems', 'Hospitals, clinics, practices and integrated delivery networks.', 40),
  ('education', 'Education & Academic', 'Schools, districts, colleges and universities.', 50),
  ('channel-partners', 'Channel, Reseller & Distributor', 'Selling through partners rather than direct to the end user.', 60),
  ('consumer', 'Consumer (B2C)', 'Selling directly to individuals.', 70);

-- sales_models: 8 entries
insert into sales_models (slug, name, description, sort_order) values
  ('inside-sales', 'Inside Sales', 'Sold remotely by phone, email and video. No routine travel.', 0),
  ('field-sales', 'Field / Outside Sales', 'In-person selling, territory travel, on-site meetings.', 10),
  ('outbound-hunting', 'Outbound / Hunting', 'Self-generated pipeline through cold outreach and prospecting.', 20),
  ('inbound-closing', 'Inbound / Closing', 'Working leads generated by marketing rather than sourcing them.', 30),
  ('account-management', 'Account Management / Farming', 'Growing and retaining existing accounts rather than winning new ones.', 40),
  ('channel-sales', 'Channel & Partner Sales', 'Recruiting and enabling resellers, distributors and partners.', 50),
  ('business-development', 'Business Development & Partnerships', 'Strategic alliances, referral networks and new market entry.', 60),
  ('solution-selling', 'Solution & Technical Selling', 'Consultative, technically involved sales with proof-of-concept work.', 70);

-- compensation_types: 7 entries
insert into compensation_types (slug, name, description, has_guaranteed_pay, sort_order) values
  ('commission-only', 'Commission Only', 'Paid purely on results. No guaranteed income.', false, 0),
  ('base-plus-commission', 'Base + Commission', 'A guaranteed base salary plus performance commission.', true, 10),
  ('draw-against-commission', 'Draw Against Commission', 'Regular advance payments offset against future commission. Provides cash flow while a pipeline builds.', true, 20),
  ('retainer', 'Retainer', 'A fixed recurring fee for an agreed scope of work.', true, 30),
  ('retainer-plus-commission', 'Retainer + Commission', 'A fixed recurring fee plus upside on results. Common for fractional roles.', true, 40),
  ('fractional', 'Fractional (Fixed Monthly)', 'A defined number of hours or days per month at a fixed rate.', true, 50),
  ('contract-project', 'Contract / Project Fee', 'A fixed fee for a defined project or engagement period.', true, 60);
